In [ ]:
import pandas as pd
import numpy as np
from keras.layers import Input, Dense
from keras.models import Model
from keras.utils import plot_model

In [ ]:
df = pd.read_csv('/content/diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
X = df.drop(columns=['Outcome', 'BMI'])

In [ ]:
y_classification = df['Outcome']
y_regression = df['BMI']

In [ ]:
inputs = Input(shape=(7,))
l1 = Dense(8, activation='relu')(inputs)
l2 = Dense(10, activation='relu')(l1)
l3 = Dense(10, activation='relu')(l2)
output_1 = Dense(1, activation='sigmoid', name='output_1')(l3)
output_2 = Dense(1, activation='linear', name='output_2')(l3)

In [ ]:
model = Model(inputs=inputs, outputs=[output_1, output_2])

In [ ]:
model.compile(optimizer='adam', loss={'output_1': 'binary_crossentropy', 'output_2': 'mse'}, metrics={'output_1':'accuracy','output_2':'mae'})

In [ ]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 7)              │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 8)              │             64 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 10)             │             90 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 10)             │            110 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_1 (Dense)          │ (None, 1)              │             11 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_2 (Dense)          │ (None, 1)              │             11 │ dense_2[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 286 (1.12 KB)

 Trainable params: 286 (1.12 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(X, y_classification, y_regression, test_size=0.2, random_state=42)

In [ ]:
model.fit(X_train, y={'output_1': y_class_train, 'output_2': y_reg_train}, epochs=10, batch_size=12)

Epoch 1/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 358.7509 - output_1_accuracy: 0.6473 - output_2_mae: 12.4555
Epoch 2/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 87.0411 - output_1_accuracy: 0.6478 - output_2_mae: 6.8304
Epoch 3/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85.8607 - output_1_accuracy: 0.6732 - output_2_mae: 7.0331
Epoch 4/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69.5926 - output_1_accuracy: 0.6504 - output_2_mae: 6.1822
Epoch 5/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58.1947 - output_1_accuracy: 0.6175 - output_2_mae: 5.7203
Epoch 6/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56.4999 - output_1_accuracy: 0.5537 - output_2_mae: 5.6445
Epoch 7/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55.4417 - output_1_accuracy: 0.5845 - output_2_mae: 5.6358
Epoch 8/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54.0798 - output_1_accuracy: 0.5523 - output_2_mae: 5.3529
Epoch 9/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51.2

In [ ]:
predictions = model.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [ ]:
r = model.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


In [ ]:
(r[0]>0.5).astype('int')

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
    

In [ ]:
(predictions[0]>0.5).astype('int')

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
    

In [ ]:
regression = predictions[1]
regression

array([[28.752132],
       [31.64028 ],
       [24.965462],
       [28.73721 ],
       [34.00003 ],
       [31.952494],
       [19.813437],
       [19.250935],
       [32.939068],
       [33.926826],
       [31.162268],
       [44.583042],
       [32.857548],
       [29.413172],
       [24.198694],
       [32.02725 ],
       [31.329256],
       [30.468605],
       [29.644192],
       [27.752262],
       [27.171505],
       [31.918278],
       [39.31417 ],
       [28.189783],
       [33.839237],
       [44.687706],
       [29.07394 ],
       [23.87669 ],
       [36.1881  ],
       [27.728365],
       [41.73724 ],
       [33.841087],
       [44.069794],
       [26.652838],
       [31.907976],
       [37.690445],
       [47.038765],
       [37.032173],
       [33.294888],
       [20.925602],
       [25.399496],
       [28.380651],
       [34.095757],
       [27.430086],
       [29.576952],
       [39.5745  ],
       [35.33742 ],
       [31.8176  ],
       [28.728956],
       [42.07518 ],


In [ ]:
results = pd.DataFrame({'Actual': y_class_test, 'Predicted':(predictions[0]>0.5).astype(int).flatten(), 'actual_regression':y_reg_test, 'predict_regression':regression.flatten()})

In [ ]:
results

Actual  Predicted  actual_regression  predict_regression
668       0          1               34.0           28.752132
324       0          1               35.7           31.640280
624       0          0               30.8           24.965462
690       0          0               24.6           28.737209
473       0          0               29.9           34.000031
..      ...        ...                ...                 ...
355       1          0               30.4           37.644329
534       0          1               33.3           26.732094
344       0          0               36.8           26.404213
296       1          1               28.0           34.303627
462       0          1               35.3           35.013634

[154 rows x 4 columns]